export {
  createToolRouter,
  withAutoAppend,
  defineTool,
  hasNoOtherToolCalls,
} from "./router";

export type {
  ToolDefinition,
  ToolWithHandler,
  ToolMap,
  ToolNames,
  RawToolCall,
  ParsedToolCall,
  ParsedToolCallUnion,
  AppendToolResultFn,
  ToolHandlerResponse,
  ToolHandlerContext,
  ToolHandler,
  ActivityToolHandler,
  ToolArgs,
  ToolResult,
  ToolCallResult,
  InferToolResults,
  ToolCallResultUnion,
  ProcessToolCallsContext,
  PreToolUseHookResult,
  PostToolUseFailureHookResult,
  ToolHooks,
  PreToolUseHookContext,
  PreToolUseHook,
  PostToolUseHookContext,
  PostToolUseHook,
  PostToolUseFailureHookContext,
  PostToolUseFailureHook,
  ToolRouterHooks,
  ToolRouterOptions,
  ToolRouter,
} from "./types";
